version: "3"
services:
  redis:
    image: "redis:alpine"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - db

volumes:
  postgres_data: